#keep user and database configurations here
default_wait_time: 10
default_env: 'www-dev5.airmiles.ca/arrow/'
default_start_page: 'Home'
default_collector_number: 51000088201
default_pin: 1111

#local environment information
local_wait_time: 10
local_env: 'localhost:8080/arrow/'
local_start_page: 'Home'
local_collector_number: 51000088201
local_pin: 1111


#page element ids and css which might change
header_collector_number_input: header-collector-number-input

###############     Footer (link name: ids) ##################
#Earn Miles Upper Footer Links ex/ link name (id/src/href) : value

AIR MILES logo: /arrow/webresource/v2/img/logo-am-footer.png
AIR MILES Shops: id_upper-footer-earnmiles-online
In Store: id_upper-footer-earnmiles-in-store
airmilesshops.ca: id_upper-footer-earnmiles-online
Payment Products: id_upper-footer-earnmiles-payment-product
Offers & Promotions: id_upper-footer-earnmiles-promotion
Promotional Sponsors: id_upper-footer-earnmiles-sponsor-near
Buy Miles: id_upper-footer-earnmiles-buy-miles
Deposit Rewards Miles: id_upper-footer-account-deposit-miles
Inspired Living: href_/arrow/InspiredLivingSplash?splashId=2600012&changeLocale=en_CA

#Redeem Miles Upper Footer Links ex/ link name (id/src/href) : value

AIR MILES Cash: id_upper-footer-rewards-cash
Dream Rewards: id_upper-footer-rewards-dream
Set your balance preference: id_upper-footer-rewards-set-balance
Deals & More: href_/arrow/DealsAndMore?selectedCategoryId=cat670038
Travel: href_/arrow/TravelOneFlightHome?selectedCategoryId=cat670036
Gift Guide: href_/arrow/RewardsGiftGuide?tgi=300031&selectedCategoryId=cat720060

#Need Help Upper Footer Links ex/ link name (id/src/href) : value

Sign In: id_upper-footer-needhelp-signin
Browse FAQs: href_/arrow/Help
Self-Serve Tools: href_/arrow/SelfServe
Learn How AIR MILES Works: id_upper-footer-needhelp-learn-how
Live Chat: id_footer-live-chat-menuitem
Contact Us: id_footer-contact-us



